export const CHANGE_HOME_DATA = 'home/CHANGE_HOME_DATA'
export const ADD_HOME_LIST = 'home/ADD_HOME_LIST'
export const TOGGLE_SHOW_SCROLL_TOP = 'home/TOGGLE_SHOW_SCROLL_TOP'
export const SPINICON_ROTATE = 'home/SPINICON_ROTATE'
